AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.1
  Exclude:
    - 'db/schema.rb'

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
