version: 2.1

orbs:
  ruby: circleci/ruby@1.0.0

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          FACEBOOK_KEY: ''
          FACEBOOK_SECRET: ''
          DATABASE_PASSWORD: 'bookstore_password'
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: rails_user
          POSTGRES_PASSWORD: 'bookstore_password'

caches:
  - &bundle_cache_strict v1-bundle-{{ checksum "Gemfile.lock" }}
  - &bundle_cache_fallback v1-bundle

commands:
  prepare:
    steps:
      - checkout
      # - run:
      #     name: Install package dependencies
      #     command: |
      #       sudo apt-get update -qq && \
      #       sudo apt-get install -y --no-install-recommends chromedriver
      - run: chromedriver -v
      - run: gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)" --no-doc
      - restore_cache:
          keys:
            - *bundle_cache_strict
            - *bundle_cache_fallback
      - run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs $(nproc) --retry 3
      - save_cache:
          key: *bundle_cache_strict
          paths:
            - vendor/bundle
      - run:
          name: Set up DB
          command: |
            bin/rails db:create
            bin/rails db:schema:load
  save-coverage:
    steps:
      - store_artifacts:
          path: ~/repo/spec/coverage
          destination: coverage
  save-capybara-artifacts:
    steps:
      - store_artifacts:
          path: ~/repo/tmp/capybara
          destination: capybara

jobs:
  build-test-coverage:
    executor: default
    steps:
      - prepare
      - ruby/rspec-test
      - save-capybara-artifacts
      - save-coverage

workflows:
  version: 2.1
  build:
    jobs:
      - build-test-coverage
