version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          RAILS_ENV: test
          FACEBOOK_KEY: ''
          FACEBOOK_SECRET: ''
          DATABASE_PASSWORD: 'bookstore_password'
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: rails_user
          POSTGRES_PASSWORD: 'bookstore_password'

caches:
  - &bundle_cache_strict v1-bundle-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
  - &bundle_cache_fallback v1-bundle

commands:
  prepare:
    steps:
      - checkout
      # - run:
      #     name: Install package dependencies
      #     command: |
      #       sudo apt-get update -qq && \
      #       sudo apt-get install -y --no-install-recommends chromedriver
      - run: chromedriver -v
      - run: gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)" --no-doc
      - restore_cache:
          keys:
            - *bundle_cache_strict
            - *bundle_cache_fallback
      - run: |
          bundle config set path 'vendor/bundle'
          bundle install --jobs $(nproc) --retry 3
      - save_cache:
          key: *bundle_cache_strict
          paths:
            - vendor/bundle
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load

  run_specs:
    steps:
      - run:
          name: Run specs
          command: |
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format RspecJunitFormatter \
                              --out test-results/rspec/results.xml \
                              --format progress \
                              $TEST_FILES
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: ~/repo/spec/coverage
      - store_artifacts:
          path: ~/repo/tmp/capybara

jobs:
  run_specs:
    executor: default
    steps:
      - prepare
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - run_specs
